spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instanceId: ${spring.application.name}
        hostname: localhost
---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eventuate

---
---
# spring:
#   datasource:
#      hikari:
#       jdbc-url: jdbc:h2:~/testdb
    
   
#   jpa:
#    show-sql: true

spring:
  datasource:
    platform: 
    url: jdbc:postgresql://localhost:5432/mydb
    username: 
    password: 
  jpa:
   show-sql: true
   hibernate.ddl-auto: update

---
spring:
  cloud:
    stream:
      bindings:
        paymentsChannel:
         binder: rabbit
         destination: payments
         content-type: application/json
         
---
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0   
        

